### ISSUE TITLE
Enhancement: Concept (no code yet): GCode Viewer

### ISSUE THREAD

**Issue by ghost** [andrewhodel/reprapweb#5]
https://github.com/hudbrog/gCodeViewer  looks like a great widget to integrate next to the STL viewer for checking GCode.

**Comment by openhardwarecoza** [comment]
On second thought, using addClass('disabled'); and removeClass('disabled'); would be even more elegant.  Two divs, one for STL viewer and one for Gcode viewer.   If you upload GCode it disables the STL viewer div and enables Gcode viewer.   
If I upload a STL, after processing to GCode we swop the two divs again so GCode viewer comes into view before you git print

**Comment by openhardwarecoza** [comment]
Right, so in my fork of Reprapweb I've done a lot of refactoring of the UI to make it a little cleaner.  However I made sure to use the same element names for existing things like the canvas where the STL preview is shown, etc.   Where I added elements (like the new temperature displays, XYZE coordinates, etc) these are of course missing from the upstream one so maybe work on integration from my fork...  Not saying you have to but if you do it should be easy to port it into either fork.

In my fork I added a lot of addClass.disabled and removeClass.disabled to elements such as the Open STL, Open GCODE, in order to for example disable the Prepare print (aka Slice) button if a GCode file is loaded (as you wouldnt want to slice gcode) and disabling the print and slice buttons until a file is loaded...
The functions in main.js (https://github.com/openhardwarecoza/reprapweb/blob/master/i/main.js) is where we can do most of the work to show the STL viewer when STL is uploaded,   and in turn hide the STL viewer and show a GCode viewer once a) a GCode file is uploaded or b) once A STL has been Sliced

1.  Upload and STL:

1.1  Around line 318 in my main.js linked above:  
```socket.on('stlUploadSuccess', function (data) {```
1.2 We can add the logic here to activate features of "I have an STL loaded":
1.2.1  Display the STL viewer
1.2.2  Activate the Slice button (called Prepare for Printing in my fork - I hide the slicing settings on a modal div else it clutters the UI too much (like the original) so this button toggles the modal)
1.2.3 Allow the user to slice the file. 

2.1 Around line 427 in my main.js - place we can add logic WHILE the slice is being performed (maybe start to gray out the STL viewer, or overlay onto it a CONVERTING TO GCODE)

3.1  Around line 170 in my main.js:  Code when the Slice is completed.  This would be a good time to add code to disable the canvas div for the STL viewer and activate a GCode viewer div
This is also where we remove the "disabled" class from the Print button (line 168 in my main.js) ```('#sendToPrinter').removeClass('disabled');```

I love the simplicity and neatness of the reprapweb codebase so it should be easy to add a GCode viewer

Other notes:

Once a STL is uploaded its saved in ./workingStl.stl and after being sliced its saved as ./workingStl.gcode 

This constant naming means in the function around line 170 in main.js we can open a gcode viewer that always just loads workingStl.gcode?

**Comment by openhardwarecoza** [comment]
Volunteers from https://plus.google.com/104034368033227202956/posts/PNx8oa1btS7 should join this effort shortly (:
